### ISSUE TITLE
Javascript and GPL

### ISSUE THREAD

**Issue by viljoviitanen** [Qvazar/js-untar#1]
Hello,

What's your stance, as the author of a gpl javascript library, on whether just using the library in an app forces the app to be released as gpl? Googling finds opinions both ways.

My app is https://github.com/viljoviitanen/freeotp-export and I include your library directly from your repo with rawgit https://github.com/viljoviitanen/freeotp-export/blob/master/export.html#L29 and then use it like this: https://github.com/viljoviitanen/freeotp-export/blob/master/export.html#L133

If you consider using your gpl library forces the app to be gpl, I'll change the license of my app to gpl.

**Comment by Qvazar** [comment]
Hi,

I've been reading up a bit on GPL and JavaScript, and it seems to cause a lot of headaches. So I've changed to the MIT license, which most other JS libraries use.
Use the library as you wish :)

**Comment by viljoviitanen** [comment]
Thanks! 👍
